permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown
# add at 2014年10月28日 20:21:11
highlighter: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: daniel
  email: xiaofa29@gmail.com
  link: http://truewaregithub.io
  weibo: http://weibo.com/
  github: http://github.com/trueware

# 站点信息
title: daniel的博客 
description: daniel的博客
url: http://truewaregithub.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: https://avatars0.githubusercontent.com/u/4661513?v=2&u=40347d70479688c71a87b1a0e096463613eb8c87&s=140
#favicon: http://yansu-uploads.stor.sinaapp.com/imgs/favicon.ico

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
#disqus:
#  shortname: suyan-zh

# 主题设置，自动激活某个标签
#active: 技术
active: 学术

# 首页除了最新文章外显示分类
#cates: 
#  - Python
# - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
